public class BI_PSPB_NotificatinRmdConstantsCtrl {
    public static string actionTypeGeneral = System.Label.BI_PSPB_General;
    public static string actionTypeUnRead = System.Label.BI_PSPB_UnRead;
    public static string actionTypeAction = System.Label.BI_PSPB_Action;
    public static string actionTypeNotificatonTypeAction = System.Label.BI_PSPB_ActionRequiredValue;
    public static String actionDqliNotificationSubject= system.Label.BI_PSPB_ActionDlqiNotification;
    public static string daysCountOfTreatment = System.Label.BI_PSPB_DaysCountofTreatment;
    public static string dlqiQuestionName = System.Label.BI_PSP_DlqiCategory;
    public static string inProgressType = System.Label.BI_PSP_InProgressTxt;
    public static string dlqi = System.Label.BI_PSP_AssessmentDlqi;
    public static string video = System.Label.BI_PSPB_Video;
    public static String generalDemonstrationVideoSubject = System.Label.BI_PSPB_GeneralDemonstrationVideo;
    public static string notificationStatusComplete = System.Label.BI_PSP_Completed;
    public static String actionTreatmentDate = System.Label.BI_PSPB_ActionTreatmentDate;
    public static String actionTreatmentDueTwentyFour = System.Label.BI_PSPB_ActionDueTwentyFour;
    public static String actionTreatmentDueSeventyTwo = System.Label.BI_PSPB_ActionDueSeventyTwo;
    public static String statusDateOfTreatment = System.Label.BI_PSP_DateOfTreatment;
    public static String dayOfTreatment = 'Day of Treatment';
    public static String pastDueDate = System.Label.BI_PSPB_PastDueDate;
    public static String pastDueDateTwo = System.Label.BI_PSPB_PastDueDateTwo;
    // Error Messages
    public static String severityInfo = 'INFO';
    public static String severityError  = 'ERROR';
    public static string errorMsgRecordNotFound = System.Label.BI_PSPB_EnrolleRecNotFound;
    public static string errorMsgSymptomTrackerNotFound = System.Label.BI_PSP_SymptomTrackerError;
    public static String recordNotFound = System.Label.BI_PSP_RecordNotFoundMsg;
    public static string errorTreatmentReminderSched = 'Failed Treatment reminder schedule';
    public static string errorTreatmentReminderService = 'Failed Treatment reminder service';
    public static string errorCreatingTask = 'Error while creating tasks';
    public static string errorUpdatingTask = 'Error while updating tasks';
}