/**
 * @description This class defines constants used in the Symptom Module.
 * @history
 * Version   Author         Date         Detail       Description
 * 1.0        Karthikeyan       25-07-2024   Created      Initial Version
 */
public  class  BI_PSP_SymptomTrackerConstantCtrl {
  public static String error = System.Label.BI_PSP_ConsoleError;
  public static String inActiveRecord = System.Label.BI_PSP_Inactive;
  public static String checkValues = System.Label.BI_PSP_CheckValues;
  public static String symptomErrorMsg = System.Label.BI_PSP_SymptomTrackerError;
  public static String gppErrorMsg = System.Label.BI_PSP_GppValuesErrorMsg;
  public static String careProgramErrorMsg = System.Label.BI_PSP_SymptomTrackerError;
  public static String carePlanErrorMsg = System.Label.BI_PSP_CarePlanErrorMsg;
  public static String patientErrorMsg = System.Label.BI_PSP_PatientErrorMsg;
  public static String contentErrorMsg = System.Label.BI_PSP_ApplicationPhotoMsg;
  public static String applicationPhotoMsg = System.Label.BI_PSP_ApplicationPhotoMsg;
  public static String bodyPartsErrorMsg = System.Label.BI_PSP_BodyPartsErrorMsg;
  public static String checkUniqueDate = System.Label.BI_PSP_CheckUnquieDate;
  public static String checkGender = System.Label.BI_PSP_Gender;
  public static String symptomRecordType = System.Label.BI_PSP_Symptom;
  public static String inActive = System.Label.BI_PSP_AcitveRecord;
  public static String activeLable = System.Label.BI_PSP_Active;
  public static String fileName = System.Label.BI_PSP_UploadedFilePng;
  public static String fileNamePath = System.Label.BI_PSP_UploadedFile;
  public static String symptomTrackerInactive = System.Label.BI_PSPB_EnrolleeCaregiverStatusInactive;
  public static String latestRecord = System.Label.BI_PSP_LatestRecords;
  public static String alleryRecord = System.Label.BI_PSP_AllergyDatas;
  public static String stausChange = System.Label.BI_PSP_SymptomUpdateStatus; 
  public static final String LOG_SEVERITY_ERROR  = 'ERROR';
}